config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only:[:create, :destroy]
  get '/logout' => 'sessions#destroy', as: 'logout'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#fail'

  resources :articles
  resources :users
  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    User.find_or_create_by(provider:auth[:provider], uid:auth[:uid]) do |user|
      user.name = auth[:info][:name]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= session[:user_id].try{|id| User.find(id)}
  end
  helper_method :current_user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :author, :published_at, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    # raise env['omniauth.auth'].to_yaml
    user = User.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_url, notice:'Log in successfully.'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice:'Log out successfully.'
  end
  def fail
    redirect_to root_url, alert:'Auth fails.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :provider, :uid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.haml
= simple_form_for(@article) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :author
    = f.input :published_at
    = f.input :content

  .form-actions
    = f.button :submit

app/views/articles/edit.html.haml
.page-header
  = link_to articles_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @article, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing article

= render 'form'

app/views/articles/index.html.haml
.page-header
  = link_to new_article_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Article
  %h1 Listing articles

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Author
        %th Published at
        %th Content
        %th
        %th
        %th

    %tbody
      - @articles.each do |article|
        %tr
          %td= article.name
          %td= article.author
          %td= article.published_at
          %td= article.content
          %td= link_to 'Show', article
          %td= link_to 'Edit', edit_article_path(article)
          %td= link_to 'Destroy', article, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/articles/new.html.haml
.page-header
  = link_to articles_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New article

= render 'form'

app/views/articles/show.html.haml
.page-header
  = link_to articles_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_article_path(@article), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show article

%dl.dl-horizontal
  %dt Name:
  %dd= @article.name
  %dt Author:
  %dd= @article.author
  %dt Published at:
  %dd= @article.published_at
  %dt Content:
  %dd= @article.content

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    %title my_omniauth_241

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{:type => "button", :data => {:toggle => "collapse", :target => "#navbar"}, :aria => {:expanded => "false", :controls => "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Project name", "#", :class => "navbar-brand"
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => "#"} Home
            %li
              %a{:href => "#about"} About
            %li
              %a{:href => "#contact"} Contact
          %ul.nav.navbar-nav.navbar-right
            - if current_user
              %li= link_to "profile #{current_user.name}", current_user
              %li= link_to "Logout", logout_path
            - else
              %li= link_to 'sign in with douban', '/auth/douban'
    .container
      - flash.each do |name, msg|
        = content_tag :div, :class => "alert alert-#{%w[alert error].include?(name.to_s) ? "danger" : "success" } alert-dismissable", :role => "alert" do
          %button.close{:type => "button", :data => {:dismiss => "alert"} }
            %span{:aria => {:hidden => "true"} } &times;
            %span.sr-only Close
          = msg
      = yield

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :provider
    = f.input :uid

  .form-actions
    = f.button :submit

app/views/users/edit.html.haml
.page-header
  = link_to users_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @user, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing user

= render 'form'

app/views/users/index.html.haml
.page-header
  = link_to new_user_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New User
  %h1 Listing users

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Provider
        %th Uid
        %th
        %th
        %th

    %tbody
      - @users.each do |user|
        %tr
          %td= user.name
          %td= user.provider
          %td= user.uid
          %td= link_to 'Show', user
          %td= link_to 'Edit', edit_user_path(user)
          %td= link_to 'Destroy', user, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/users/new.html.haml
.page-header
  = link_to users_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New user

= render 'form'

app/views/users/show.html.haml
.page-header
  = link_to users_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_user_path(@user), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show user

%dl.dl-horizontal
  %dt Name:
  %dd= @user.name
  %dt Provider:
  %dd= @user.provider
  %dt Uid:
  %dd= @user.uid